name: replace_me
cluster_env_name: replace_me

image:
  repository: replace_me
  tag: replace_me
  pullPolicy: IfNotPresent
  port: 8080
  requestCpu: 100m
  limitCpu: 200m
  requestMemory: 256Mi
  limitMemory: 512Mi

service:
  type: LoadBalancer
  port: 8080

hpa:
  enabled: false
  min: 1
  max: 2
  cpu: 60

ingress:
  enabled: false
  name: replace_me
  host: replace_me
  path: /
  environment: replace_me
  tls: false