name: REPLACE_ME
cluster_env_name: REPLACE_ME
deployment:
  replicas: 1
  image:
    repository: nemogpt/nemo-common-helm
    tag: latest
    pullPolicy: IfNotPresent
    port: 8080
    requestCpu: 100m
    limitCpu: 200m
    requestMemory: 256Mi
    limitMemory: 512Mi

hpa:
  min: 1
  max: 2
  cpu: 60



service:
  type: LoadBalancer
  port: 8080
