apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nemo-common-helm.fullname" . }}
  labels:
    app: {{ include "nemo-common-helm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nemo-common-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nemo-common-helm.name" . }}
    spec:
      containers:
        - name: {{ include "nemo-common-helm.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
          resources:
            requests:
              memory: {{ .Values.image.requestMemory }}
              cpu: {{ .Values.image.requestCpu }}
            limits:
              memory: {{ .Values.image.limitMemory }}
              cpu: {{ .Values.image.limitCpu }}
