apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-common-helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nemo-common-helm.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}