apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.image.port | default 8080 }}